In [1]:
import pandas as pd
base = pd.read_csv('house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [2]:
base.shape

(21613, 21)

In [3]:
X = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [4]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [5]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [6]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

/home/claesia/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/claesia/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [7]:
X

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [8]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [9]:
import tensorflow as tf

In [10]:
colunas = [tf.feature_column.numeric_column('x', shape = [1])]

In [11]:
colunas

[_NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [12]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpin9f9p6r', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f9ebfe8dc88>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [13]:
from sklearn.model_selection import train_test_split #70% treinamento 30% teste

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
# test_size quantidade passada para teste

In [39]:
X_train.shape

(15129, 1)

In [40]:
X_test.shape

(6484, 1)

In [41]:
y_train.shape

(15129, 1)

In [42]:
y_test.shape

(6484, 1)

In [43]:
train_function = tf.estimator.inputs.numpy_input_fn({'x': X_train}, y_train, batch_size = 32, num_epochs = None, shuffle = True)
# no shuffle = True ele sorteia os registros, sorteir 32 e mando o batch, depois mais 32... pega aleatoriamento
#{} mesmo nome de determinou no feature_columns

In [44]:
test_function = tf.estimator.inputs.numpy_input_fn({'x': X_test}, y_test, batch_size = 32, num_epochs = 1000, shuffle = False)
# num_epocs controca quantas vezes será feito o treinamento

In [45]:
regressor.train(input_fn = train_function, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpin9f9p6r/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 10000 into /tmp/tmpin9f9p6r/model.ckpt.
INFO:tensorflow:loss = 19.213757, step = 10001
INFO:tensorflow:global_step/sec: 779.35
INFO:tensorflow:loss = 11.0097885, step = 10101 (0.130 sec)
INFO:tensorflow:global_step/sec: 943.581
INFO:tensorflow:loss = 12.05861, step = 10201 (0.106 sec)
INFO:tensorflow:global_step/sec: 942.472
INFO:tensorflow:loss = 9.002465, step = 10301 (0.106 sec)
INFO:tensorflow:global_step/sec: 943.736
INFO:tensorflow:loss = 13.068051, step = 10401 (0.105 sec)
INFO:tensorflow:global_step/sec: 820.456
INFO:tensorflow:loss = 13.144909, step = 10501 (0.125 sec)
INFO:tensorflow:global_step/sec: 616.507
INFO:tensorflow:loss =

INFO:tensorflow:global_step/sec: 891.83
INFO:tensorflow:loss = 42.6343, step = 17901 (0.111 sec)
INFO:tensorflow:global_step/sec: 876.393
INFO:tensorflow:loss = 18.740229, step = 18001 (0.112 sec)
INFO:tensorflow:global_step/sec: 975.762
INFO:tensorflow:loss = 7.854171, step = 18101 (0.104 sec)
INFO:tensorflow:global_step/sec: 942.218
INFO:tensorflow:loss = 8.725031, step = 18201 (0.106 sec)
INFO:tensorflow:global_step/sec: 880.479
INFO:tensorflow:loss = 8.175825, step = 18301 (0.113 sec)
INFO:tensorflow:global_step/sec: 914.667
INFO:tensorflow:loss = 14.675655, step = 18401 (0.110 sec)
INFO:tensorflow:global_step/sec: 979.691
INFO:tensorflow:loss = 9.243334, step = 18501 (0.102 sec)
INFO:tensorflow:global_step/sec: 896.828
INFO:tensorflow:loss = 9.773117, step = 18601 (0.113 sec)
INFO:tensorflow:global_step/sec: 934.901
INFO:tensorflow:loss = 7.77318, step = 18701 (0.106 sec)
INFO:tensorflow:global_step/sec: 1023.84
INFO:tensorflow:loss = 13.224071, step = 18801 (0.097 sec)
INFO:tenso

In [46]:
train_metrics = regressor.evaluate(input_fn = train_function, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-22-01:36:12
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpin9f9p6r/model.ckpt-20000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-22-01:36:19
INFO:tensorflow:Saving dict for global step 20000: average_loss = 0.5171162, global_step = 20000, label/mean = 0.0015062756, loss = 16.547718, prediction/mean = -0.0044445004
INFO:tensorflow:Saving 'checkpoint_pa

In [47]:
test_metrics = regressor.evaluate(input_fn = test_function, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-22-01:36:22
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpin9f9p6r/model.ckpt-20000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-22-01:36:32
INFO:tensorflow:Saving dict for global step 20000: average_loss = 0.4843942, global_step = 20000, label/mean = -0.0033818043, loss = 15.500614, prediction/mean = -0.008281826
INFO:tensorflow:Saving 'checkpoint_pa

In [48]:
train_metrics

{'average_loss': 0.5171162,
 'label/mean': 0.0015062756,
 'loss': 16.547718,
 'prediction/mean': -0.0044445004,
 'global_step': 20000}

In [49]:
test_metrics

{'average_loss': 0.4843942,
 'label/mean': -0.0033818043,
 'loss': 15.500614,
 'prediction/mean': -0.008281826,
 'global_step': 20000}

In [50]:
import numpy as np
novas_casas = np.array([[800], [900], [1000]])
novas_casas

array([[ 800],
       [ 900],
       [1000]])

In [51]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
novas_casas = scaler_x.fit_transform(novas_casas)
novas_casas

/home/claesia/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/claesia/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.22474487],
       [ 0.        ],
       [ 1.22474487]])

In [52]:
funcao_previsao = tf.estimator.inputs.numpy_input_fn({'x': novas_casas}, shuffle = True)

In [53]:
previsoes = regressor.predict(input_fn = funcao_previsao)

In [54]:
previsoes

<generator object Estimator.predict at 0x7f9eabd3eeb8>

In [56]:
list(previsoes)

[]

In [57]:
for p in regressor.predict(input_fn = funcao_previsao):
    #print(p['predictions'])
    print(scaler_y.inverse_transform(p['predictions']))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpin9f9p6r/model.ckpt-20000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[220481.86]
[538029.94]
[855578.]
