In [1]:
import pandas as pd
base = pd.read_csv('house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [2]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [4]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [5]:
base = pd.read_csv("house-prices.csv", usecols = colunas_usadas)

In [6]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

/home/claesia/.local/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [8]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [9]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [10]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [11]:
X = base.drop('price', axis = 1)
y = base.price

In [13]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [14]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [15]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [17]:
import tensorflow as tf

In [19]:
colunas = [tf.feature_column.numeric_column(key= c) for c in previsores_colunas]

In [21]:
print(colunas[1])

_NumericColumn(key='bathrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [22]:
from sklearn.model_selection import train_test_split #70% treinamento 30% teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
# test_size quantidade passada para teste

In [23]:
X_train.shape

(15129, 16)

In [24]:
y_train.shape

(15129,)

In [25]:
X_test.shape

(6484, 16)

In [29]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_train, y = y_train, batch_size = 32,
                                                        num_epochs= None, shuffle = True)

In [30]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = X_test, y = y_test, batch_size = 32,
                                                        num_epochs= 10000, shuffle = False)

In [31]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpe8b4egij', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f90057f2eb8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [32]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpe8b4egij/model.ckpt.
INFO:tensorflow:loss = 0.11304103, step = 1
INFO:tensorflow:global_step/sec: 248.769
INFO:tensorflow:loss = 0.07904287, step = 101 (0.403 sec)
INFO:tensorflow:global_step/sec: 119.701
INFO:tensorflow:loss = 0.019965759, step = 201 (0.841 sec)
INFO:tensorflow:global_step/sec: 56.8708
INFO:tensorflow:loss = 0.017127803, step = 301 (1.754 sec)
INFO:tensorflow:global_step/sec: 96.7361
INFO:tensorflow:loss = 0.0076081348, step = 401 (1.057 

INFO:tensorflow:global_step/sec: 298.022
INFO:tensorflow:loss = 0.012993171, step = 6901 (0.329 sec)
INFO:tensorflow:global_step/sec: 303.292
INFO:tensorflow:loss = 0.3385135, step = 7001 (0.327 sec)
INFO:tensorflow:global_step/sec: 324.479
INFO:tensorflow:loss = 0.013019069, step = 7101 (0.309 sec)
INFO:tensorflow:global_step/sec: 303.076
INFO:tensorflow:loss = 0.010070657, step = 7201 (0.329 sec)
INFO:tensorflow:global_step/sec: 337.741
INFO:tensorflow:loss = 0.017558217, step = 7301 (0.295 sec)
INFO:tensorflow:global_step/sec: 311.184
INFO:tensorflow:loss = 0.00976325, step = 7401 (0.324 sec)
INFO:tensorflow:global_step/sec: 311.743
INFO:tensorflow:loss = 0.04181632, step = 7501 (0.319 sec)
INFO:tensorflow:global_step/sec: 334.992
INFO:tensorflow:loss = 0.019175902, step = 7601 (0.299 sec)
INFO:tensorflow:global_step/sec: 316.69
INFO:tensorflow:loss = 0.015928593, step = 7701 (0.314 sec)
INFO:tensorflow:global_step/sec: 306.574
INFO:tensorflow:loss = 0.007301126, step = 7801 (0.328 

In [33]:
metricas_treinamento = regressor.evaluate(input_fn = funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-22-02:14:32
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpe8b4egij/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-22-02:15:35
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007425811, global_step = 10000, label/mean = 0.06106185, loss = 0.023762595, prediction/mean = 0.06771785
INFO:tensorflow:Saving 'checkpoint_pa

In [34]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-22-02:15:36
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpe8b4egij/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-22-02:16:11
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007567879, global_step = 10000, label/mean = 0.060833544, loss = 0.024217213, prediction/mean = 0.06738888
INFO:tensorflow:Saving 'checkpoint_p

In [35]:
metricas_treinamento

{'average_loss': 0.0007425811,
 'label/mean': 0.06106185,
 'loss': 0.023762595,
 'prediction/mean': 0.06771785,
 'global_step': 10000}

In [36]:
metricas_teste

{'average_loss': 0.0007567879,
 'label/mean': 0.060833544,
 'loss': 0.024217213,
 'prediction/mean': 0.06738888,
 'global_step': 10000}

In [37]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_test, shuffle = False)

In [38]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [40]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpe8b4egij/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.09925117], dtype=float32)},
 {'predictions': array([0.20745766], dtype=float32)},
 {'predictions': array([0.07072555], dtype=float32)},
 {'predictions': array([0.08136765], dtype=float32)},
 {'predictions': array([0.05529615], dtype=float32)},
 {'predictions': array([0.09232805], dtype=float32)},
 {'predictions': array([0.02665144], dtype=float32)},
 {'predictions': array([0.05580965], dtype=float32)},
 {'predictions': array([0.04173935], dtype=float32)},
 {'predictions': array([0.03172369], dtype=float32)},
 {'predictions': array([0.03280839], dtype=float32)},
 {'predictions': array([0.03948076], dtype=float32)},
 {'predictions': array([0.08171172], dtype=float32)},
 {'predictions': array([0.10399359], dtype=float32)},
 {'predictions': array([0.10447659], dtype=float32)},
 {'predictions': array([0.03567988], dtype=float32)},
 {'predictions': array([0.09813448], dtype=float32)},
 {'predictions': array([0.02605662], dtype=float32)},
 {'predictions': array([0.06

In [42]:
valores_previsoes = []
for p in regressor.predict(input_fn = funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpe8b4egij/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [43]:
valores_previsoes

[array([0.09925117], dtype=float32),
 array([0.20745766], dtype=float32),
 array([0.07072555], dtype=float32),
 array([0.08136765], dtype=float32),
 array([0.05529615], dtype=float32),
 array([0.09232805], dtype=float32),
 array([0.02665144], dtype=float32),
 array([0.05580965], dtype=float32),
 array([0.04173935], dtype=float32),
 array([0.03172369], dtype=float32),
 array([0.03280839], dtype=float32),
 array([0.03948076], dtype=float32),
 array([0.08171172], dtype=float32),
 array([0.10399359], dtype=float32),
 array([0.10447659], dtype=float32),
 array([0.03567988], dtype=float32),
 array([0.09813448], dtype=float32),
 array([0.02605662], dtype=float32),
 array([0.06192797], dtype=float32),
 array([0.07594808], dtype=float32),
 array([0.03697045], dtype=float32),
 array([0.13068593], dtype=float32),
 array([0.07975651], dtype=float32),
 array([0.02860239], dtype=float32),
 array([0.08428698], dtype=float32),
 array([0.01124196], dtype=float32),
 array([0.06003357], dtype=float32),
 

In [45]:
import numpy as np
valores_previsoes= np.asarray(valores_previsoes).reshape(-1, 1)

In [46]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[ 831790.2 ],
       [1656864.6 ],
       [ 614282.3 ],
       ...,
       [1090364.2 ],
       [ 171639.73],
       [ 656096.3 ]], dtype=float32)

In [48]:
y_test

15243    0.053115
16193    0.228197
7976     0.073443
10406    0.036584
20786    0.044066
5599     0.036066
2810     0.013115
4402     0.057705
21519    0.045246
6243     0.127869
6394     0.032780
7784     0.042623
15235    0.112787
7263     0.069692
20761    0.087082
727      0.022295
9901     0.086557
17367    0.013770
4567     0.068721
19291    0.078689
6956     0.026951
4559     0.155410
19398    0.072131
11786    0.021312
11963    0.072131
5483     0.007213
16084    0.051148
11639    0.045246
5147     0.020984
11126    0.023180
           ...   
13000    0.028852
11692    0.131934
3410     0.041311
17929    0.032125
2561     0.033443
16615    0.077377
16173    0.079738
9493     0.059016
1450     0.018361
19478    0.036197
13420    0.026230
80       0.041311
12647    0.037574
2219     0.042361
1902     0.053770
20960    0.066230
10227    0.019554
18763    0.041180
2554     0.024918
17827    0.114754
17882    0.057967
14776    0.052131
19057    0.042557
15486    0.034098
14739    0

In [50]:
y_test.shape

(6484,)

In [52]:
y_test2 = y_test.values.reshape(-1,1)
y_test2.shape

(6484, 1)

In [53]:
y_test2 = scaler_y.inverse_transform(y_test2)

In [56]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test2, valores_previsoes)

In [58]:
mae

138006.69646881687